routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RegistrationController;

use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\DataKategoriController;


use App\Http\Controllers\AuthenticationController;

use App\Http\Controllers\DashboardPenulisController;
use App\Http\Controllers\PostinganPenulisController;
use App\Http\Controllers\HapusKomentarController;
//use App\Http\Controllers\PenulisController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'lihat']);
Route::get('/detailpost/{idpost}', [HomeController::class, 'detail']);
Route::get('/cari', [HomeController::class, 'searching']);
Route::post('/detailpost/{idpost}', [HomeController::class, 'tambahKomentar']);
Route::get('/kategori/{idkategori}', [HomeController::class, 'sortKategori']);


//penulis
Route::middleware('penulis')->group(function () {
    Route::get('/penulis/dashboard', [DashboardPenulisController::class, 'index']);
    Route::get('/penulis/editprofile', [DashboardPenulisController::class, 'tampilFormEdit']);
    Route::post('/penulis/editprofile', [DashboardPenulisController::class, 'simpan']);
    Route::get('/penulis/post', [DashboardPenulisController::class, 'daftarPostingan']);
    Route::get('/penulis/edit/{idpost}', [DashboardPenulisController::class, 'edit']);
    Route::get('/penulis/hapus/{idpost}', [DashboardPenulisController::class, 'hapus']);

    Route::get('/penulis/tambahpost', [PostinganPenulisController::class, 'formTambah']);
    Route::post('/penulis/tambahpost', [PostinganPenulisController::class, 'tambahPost']);
    Route::post('/penulis/edit/{idpost}', [PostinganPenulisController::class, 'simpanEdit']);

    Route::get('/detailpost/hapus/{idkomentar}', [HapusKomentarController::class, 'hapusKomentar']);
    Route::get('/cetak/{idpost}', [PostinganPenulisController::class, 'generatePDF']);
});

Route::get('/logout', function () {
    auth()->logout();
    return redirect('/');
});

// Rute (url), View
Route::view('login', 'login');
Route::post('login', [AuthenticationController::class, 'login']);

Route::view('daftar', 'daftar');
Route::post('daftar', [RegistrationController::class, 'register']);

//admin
Route::middleware('admin')->group(function () {
    Route::get('/admin/dashboard', [DashboardAdminController::class, 'tampilDashboardAdmin']);
    Route::get('/admin/editprofil', [DashboardAdminController::class, 'tampilFormEdit']);
    Route::post('/admin/editprofil', [DashboardAdminController::class, 'simpan']);
    Route::get('/admin/data_penulis', [DashboardAdminController::class, 'dataPenulis']);
    Route::post('/admin/edit_penulis/{idpenulis}', [DashboardAdminController::class, 'editPassword']);
    Route::get('/admin/edit_penulis/{idpenulis}', [DashboardAdminController::class, 'tampilEditPassword']);

    Route::get('/admin/data_kategori', [DataKategoriController::class, 'dataKategori']);
    Route::post('/admin/data_kategori', [DataKategoriController::class, 'tambahKategori']);
    Route::get('/admin/edit_kategori/{idkategori}', [DataKategoriController::class, 'tampilEditKategori']);
    Route::post('/admin/edit_kategori/{idkategori}', [DataKategoriController::class, 'editKategori']);
    Route::get('/admin/hapus_kategori/{idkategori}', [DataKategoriController::class, 'hapusKategori']);
    Route::get('/admin/data_penulis/export', [DashboardAdminController::class, 'export']);

});

app/Http/Controllers/DashboardAdminController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kategori;
use Illuminate\Support\Facades\Hash;
use App\Models\Admin;
use App\Models\User;
use App\Models\Penulis;
use App\Exports\data_penulis;
use Maatwebsite\Excel\Facades\Excel;

class DashboardAdminController extends Controller
{
    public function tampilDashboardAdmin()
    {
        $user = auth()->user();
        $admin = $user->admin;
        $kategori = Kategori::withCount('post')->get();

        return view('admin.dashboard_admin', compact('user', 'admin', 'kategori'));
    }

    public function tampilFormEdit()
    {
        $user = auth()->user();
        $admin = $user->admin;

        return view('admin.edit_profil', compact('user', 'admin'));
    }

    public function simpan(Request $request)
    {
        $request->validate([
            'nama' => ['required', 'max:30'],
            'email' => ['required', 'email'],
            'password' => ['nullable'],
        ]);

        $user = auth()->user();
        $admin = $user->admin;
        $user->nama = $request->nama;
        $user->email = $request->email;
        if ($request->password) {
            $user->password = Hash::make($request->password);
        }

        $admin->save();
        $user->save();
        return back();
    }

    public function dataPenulis()
    {
        // SELECT * FROM Penulis
        $penulis = Penulis::all();

        return view('admin.data_penulis', compact('penulis'));
    }

    public function export()
	{
		return Excel::download(new data_penulis, 'datapenulis.xlsx');
	}


    public function tampilEditPassword($idpenulis)
    {
        $penulis = Penulis::find($idpenulis);
        return view('admin.edit_penulis', compact('penulis'));
    }

    public function editPassword(Request $request, $idpenulis)
    {
        $penulis = Penulis::find($idpenulis);
        $user = $penulis->user;
        $user->password = Hash::make($request->password);

        $user->save();
        return redirect('/admin/data_penulis');
    }
}

resources/views/admin/dashboard_admin.blade.php
@extends('partial.admin')

@section('menu')
	<a href="{{ url('/admin/dashboard') }}" class="active"><i class="fas fa-desktop"></i>Dashboard</a>
	<a href="{{ url('/admin/data_kategori') }}"><i class="fas fa-book"></i>Data Kategori</a>
	<a href="{{ url('/admin/data_penulis') }}"><i class="fas fa-pencil-alt"></i>Data Penulis</a>
	<a href="{{ url('/admin/editprofil') }}"><i class="fas fa-user-edit"></i>Edit Profil</a>
@endsection

@section('content')
    <h4 style="margin-top: 50px;margin-left: 335px;">REKAP JUMLAH POSTINGAN</h4>
    <table class="table table-dashboard">
        <thead>
            <tr>
                <th>
                    Kategori
                </th>
                <th style="width: 60%">
                    Banyak postingan
                </th>
            </tr>
        </thead>

        <tbody>
            @foreach ($kategori as $k)
                <tr>
                    <td>
                        {{ $k->nama }}
                    </td>
                    <td>
                        {{ $k->post_count }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/admin/data_kategori.blade.php
@extends('partial.admin')

@section('menu')
	<a href="{{ url('/admin/dashboard') }}"><i class="fas fa-desktop"></i>Dashboard</a>
	<a href="{{ url('/admin/data_kategori') }}" class="active"><i class="fas fa-book"></i>Data Kategori</a>
	<a href="{{ url('/admin/data_penulis') }}"><i class="fas fa-pencil-alt"></i>Data Penulis</a>
	<a href="{{ url('/admin/editprofil') }}" ><i class="fas fa-user-edit"></i>Edit Profil</a>
@endsection

@section('content')
	<form method="post" action="/admin/data_kategori">
		@csrf
		<table style="margin-top: 20px">
			<tr>
				<td>
					<input type="text" class="form-control" name="nama" placeholder="Nama Kategori">
				</td>
				<td style="padding-left:50px;padding-bottom: 10px">
					<button class="btn btn-primary" type="submit" style="border-radius: 2px;"><i class="fas fa-plus"></i> Tambah</button>
				</td>
			</tr>
		</table>
	</form>
	<h4 style="margin-left: 400px;margin-top:40px">DAFTAR KATEGORI</h4>
	<table class="table table-hover table-kategori">
		@foreach ($kategori as $k)
		<tr class="tr-warna">
			<td style="width: 550px">{{ $k->nama }}</td>
			<td><a href="{{ url('/admin/edit_kategori/' . $k->idkategori) }}"><i class="fas fa-pencil-alt"></i></a></td>
			<td><a href="{{ url('/admin/hapus_kategori/' . $k->idkategori) }}"><i class="fas fa-trash-alt"></i></a></td>
		</tr>
		@endforeach
	</table>
@endsection

resources/views/admin/data_penulis.blade.php
@extends('partial.admin')

@section('menu')
	<a href="{{ url('/admin/dashboard') }}"><i class="fas fa-desktop"></i>Dashboard</a>
	<a href="{{ url('/admin/data_kategori') }}"><i class="fas fa-book"></i>Data Kategori</a>
	<a href="{{ url('/admin/data_penulis') }}" class="active"><i class="fas fa-pencil-alt"></i>Data Penulis</a>
	<a href="{{ url('/admin/editprofil') }}"><i class="fas fa-user-edit"></i>Edit Profil</a>
@endsection

@section('content')
	<a href="/admin/data_penulis/export"><button name="export" class="btn btn-success mt-3">Export</button></a>
	<h4 style="margin-top: 40px;margin-bottom: -10px;margin-left: 400px;">DAFTAR PENULIS </h4>
	<table class="table table-hover data">
		@foreach ($penulis as $p)
		<tr class="tr-warna">
			<td style="width: 550px">{{ $p->user->nama }}</td>
			<td><a href="{{ url('/admin/edit_penulis/' . $p->idpenulis) }}"><i class="fas fa-key kunci"></i></a></td>
		</tr>
		@endforeach
	</table>
@endsection

resources/views/admin/edit_kategori.blade.php
@extends('partial.admin')

@section('menu')
	<a href="{{ url('/admin/dashboard') }}"><i class="fas fa-desktop"></i>Dashboard</a>
	<a href="{{ url('/admin/data_kategori') }}" class="active"><i class="fas fa-book"></i>Data Kategori</a>
	<a href="{{ url('/admin/data_penulis') }}"><i class="fas fa-pencil-alt"></i>Data Penulis</a>
	<a href="{{ url('/admin/editprofil') }}" ><i class="fas fa-user-edit"></i>Edit Profil</a>
@endsection

@section('content')
	<div class="card card-kategori">
		<form method="post" action="">
			@csrf
			<div class="card-header" style="font-weight: bold;">{{ $kategori->nama }}</div>
			<div class="card-body">
				<input type="text" class="form-control" name="nama" value="{{ $kategori->nama }}" style="width: 60%">
				<button class="btn btn-primary btn-kategori" type="submit">Edit</button>
			</div>
		</form>
	</div>
@endsection 

resources/views/admin/edit_penulis.blade.php
@extends('partial.admin')

@section('menu')
	<a href="{{ url('/admin/dashboard') }}"><i class="fas fa-desktop"></i>Dashboard</a>
	<a href="{{ url('/admin/data_kategori') }}"><i class="fas fa-book"></i>Data Kategori</a>
	<a href="{{ url('/admin/data_penulis') }}" class="active"><i class="fas fa-pencil-alt"></i>Data Penulis</a>
	<a href="{{ url('/admin/editprofil') }}"><i class="fas fa-user-edit"></i>Edit Profil</a>
@endsection

@section('content')
	<div class="card password">
		<form method="post" action="">
			@csrf
			<div class="card-header" style="font-weight: bold;">{{ $penulis->user->nama }}</div>
			<div class="card-body">
				<label style="margin-bottom: 10px">Password Baru</label>
				<input type="text" class="form-control form-pass" name="password" placeholder="Password">
				<button class="btn btn-primary editpassword" type="submit">Edit</button>
			</div>
		</form>
	</div>
@endsection

resources/views/admin/edit_profil.blade.php
@extends('partial.admin')

@section('menu')
	<a href="{{ url('/admin/dashboard') }}"><i class="fas fa-desktop"></i>Dashboard</a>
	<a href="{{ url('/admin/data_kategori') }}"><i class="fas fa-book"></i>Data Kategori</a>
	<a href="{{ url('/admin/data_penulis') }}"><i class="fas fa-pencil-alt"></i>Data Penulis</a>
	<a href="{{ url('/admin/editprofil') }}" class="active"><i class="fas fa-user-edit"></i>Edit Profil</a>
@endsection

@section('content')
    <div class="card card-profil">
        <div class="card-body">  
        	<form method="post" action="{{ url('/admin/editprofil') }}">
        		@csrf
            	<table class="edit">
            		<tr>
            			<td><i class="fas fa-user"></i></td>
            			<td>
            				<input type="text" class="form-control" name="nama" autofocus placeholder="Nama" value="{{ $user->nama }}">
            			</td>
            		</tr>
            		<tr>
            			<td><i class="fas fa-envelope"></i></td>
            			<td>
            				<input type="text" class="form-control" name="email" placeholder="Email" value="{{ $user->email }}">
            			</td>
            		</tr>
            		<tr>
            			<td><i class="fas fa-key"></i></td>
            			<td>
            				<input type="text" class="form-control" name="password" placeholder="Password">
            			</td>
            		</tr>
            		<tr>
            			<td colspan="2">
            				<center>
            					<button type="submit" class="btn btn-primary btn-edit" name="submit" value="submit">Edit</button>
            				</center>
            			</td>
            		</tr>
            	</table>
        	</form>
        </div>	
    </div>
@endsection